version: "3.3"

services:
  sql-server-db:
    container_name: sqlServerDemoApplication
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SecureAF!"
      ACCEPT_EULA: "Y"
